version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      androidx:
        patterns:
          - "androidx.*"
      kotlinx:
        patterns:
          - "org.jetbrains.kotlinx:*"
      junit:
        patterns:
          - "junit:junit"
    ignore:
      - dependency-name: "com.android.tools.build:gradle"
        update-types: ["version-update:semver-major"]
      - dependency-name: "org.jetbrains.kotlin:kotlin-gradle-plugin"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
