package com.example.networkscanner.export

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import com.example.networkscanner.model.ScanResult
import com.example.networkscanner.model.UrlDiscovery
import com.example.networkscanner.model.ScanType
import com.google.gson.GsonBuilder
import java.io.File
import java.io.FileWriter

object Exporter {

    private val gson = GsonBuilder().setPrettyPrinting().create()

    fun exportToJson(context: Context, result: ScanResult): File {
        val json = gson.toJson(result)
        val file = File(context.cacheDir, "scan_${result.timestamp}.json")
        file.writeText(json)
        return file
    }

    fun exportToCsv(context: Context, result: ScanResult): File {
        val sb = StringBuilder()
        sb.appendLine("Target,Type,Timestamp,Host,Port,Service,Banner,Status")

        val baseTarget = result.target
        val scanType = result.type.name
        val timestamp = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss", java.util.Locale.US)
            .format(java.util.Date(result.timestamp))

        if (result.type == ScanType.URL_PATH) {
            sb.appendLine("$baseTarget,$scanType,$timestamp,,,,,URL Scan")
            for (url in result.discoveredUrls) {
                sb.appendLine(",,,${url.url},${url.statusCode},,${url.title ?: ""},Found")
            }
        } else {
            for (host in result.hosts) {
                if (host.openPorts.isEmpty()) {
                    sb.appendLine("$baseTarget,$scanType,$timestamp,${host.ip},,,${host.macAddress ?: ""},Alive")
                } else {
                    for (port in host.openPorts) {
                        sb.appendLine("$baseTarget,$scanType,$timestamp,${host.ip},${port.port},${port.service ?: ""},${port.banner ?: ""},Open")
                    }
                }
            }
        }

        val file = File(context.cacheDir, "scan_${result.timestamp}.csv")
        file.writeText(sb.toString())
        return file
    }

    fun exportToTxt(context: Context, result: ScanResult): String {
        val sb = StringBuilder()
        val date = java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss", java.util.Locale.US)
            .format(java.util.Date(result.timestamp))

        sb.appendLine("╔══════════════════════════════════════╗")
        sb.appendLine("║         NetRadar Scan Report        ║")
        sb.appendLine("╚══════════════════════════════════════╝")
        sb.appendLine()
        sb.appendLine("Target:     ${result.target}")
        sb.appendLine("Scan Type:  ${result.type.label}")
        sb.appendLine("Timestamp:  $date")
        sb.appendLine()

        if (result.type == ScanType.URL_PATH) {
            sb.appendLine("─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─")
            sb.appendLine("  Discovered URLs")
            sb.appendLine("─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─")
            for (url in result.discoveredUrls) {
                val icon = when (url.statusCode) {
                    200 -> "✓"
                    301, 302 -> "↻"
                    401, 403 -> "🔒"
                    500 -> "✗"
                    else -> "?"
                }
                sb.appendLine("  $icon ${url.statusCode} ${url.url}")
                if (url.title != null) sb.appendLine("      Title: ${url.title}")
            }
        } else {
            sb.appendLine("─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─")
            sb.appendLine("  Hosts Found")
            sb.appendLine("─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─")
            for (host in result.hosts) {
                sb.appendLine()
                sb.appendLine("  📍 ${host.ip}")
                if (host.hostname != null) sb.appendLine("     Hostname: ${host.hostname}")
                if (host.macAddress != null) {
                    sb.appendLine("     MAC: ${host.macAddress} ${host.macVendor?.let { "($it)" } ?: ""}")
                }
                if (host.latencyMs != null) sb.appendLine("     Latency: ${host.latencyMs}ms")
                if (host.openPorts.isNotEmpty()) {
                    sb.appendLine("     Open Ports:")
                    for (port in host.openPorts) {
                        sb.appendLine("       • ${port.port}/tcp  ${port.service ?: ""}")
                        if (port.banner != null) sb.appendLine("         Banner: ${port.banner.take(80)}")
                    }
                }
            }
        }

        sb.appendLine()
        sb.appendLine("─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─")
        sb.appendLine("  Scan complete")
        sb.appendLine("─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─━─")
        sb.appendLine("  Generated by NetRadar v2.0")

        val file = File(context.cacheDir, "scan_${result.timestamp}.txt")
        file.writeText(sb.toString())
        return sb.toString()
    }

    fun shareFile(context: Context, file: File) {
        try {
            val uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )
            val intent = Intent(Intent.ACTION_SEND).apply {
                type = "*/*"
                putExtra(Intent.EXTRA_STREAM, uri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            context.startActivity(Intent.createChooser(intent, "Share Scan Result"))
        } catch (_: Exception) {}
    }
}
